---

- name: "Load OS-specific vars"
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: "Install Debian Gearman packages"
  apt:
    pkg: "{{ gearman_packages }}"
    state: "present"
    update_cache: "yes"
    cache_valid_time: "3600"
    install_recommends: "no"
  when: ansible_os_family == 'Debian'

- name: "Install epel repo (CentOS/Rocky/Almalinux/OracleLinux)"
  yum:
    name: "epel-release"
    state: "installed"
  when:
    - install_rpm_repositories|bool
    - ansible_os_family == 'RedHat'
    - ansible_distribution not in ['RedHat']

- name: "Add epel-release repository (RHEL)"
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version|int }}.noarch.rpm"
    state: "present"
  when:
    - install_rpm_repositories|bool
    - ansible_os_family == 'RedHat'
    - ansible_distribution in ['RedHat']

- name: "Enable crb repo on CentOS/Rocky/Almalinux >= 9"
  command: "dnf config-manager --set-enabled crb"
  when:
    - ansible_distribution in ['CentOS','Rocky','AlmaLinux']
    - ansible_facts['distribution_major_version'] >= "9"
    - install_rpm_repositories|bool

- name: "Enable crb repo on OracleLinux >= 9"
  command: "dnf config-manager --set-enabled ol9_codeready_builder"
  when:
    - ansible_distribution in ['OracleLinux']
    - ansible_facts['distribution_major_version'] >= "9"
    - install_rpm_repositories|bool

- name: "Enable crb repo on RHEL >= 9"
  command: "subscription-manager repos --enable=codeready-builder-for-rhel-9-x86_64-rpms"
  when:
    - ansible_distribution in ['RedHat']
    - ansible_facts['distribution_major_version'] >= "9"
    - install_rpm_repositories|bool

- name: "Install Enterprise Linux Gearman packages"
  yum:
    name: "{{ gearman_packages }}"
    state: "present"
  when: ansible_os_family in ['RedHat','Rocky']

- name: "Populate gearman defaults"
  template:
    src: "{{ gearman_config_src }}"
    dest: "{{ gearman_config_dest }}"
    owner: "root"
    group: "root"
  notify:
    - "Restart gearman"

- name: "Install Gearman service"
  template:
    src: "etc/init/gearman-job-server.conf"
    dest: "/etc/init/gearman-job-server.conf"
    owner: "root"
    group: "root"
  notify:
    - "Restart gearman"
  when:
    - ansible_service_mgr == "upstart"

- name: "Ensure that gearman is enabled and running"
  service:
    name: "{{ gearman_service }}"
    enabled: "yes"
    state: "started"

- name: "Flush handlers"
  meta: flush_handlers
